local:
  upload_folder: './elo/'

  credential_file: './credential/kokoichiroanalysis-c15f6fd5f796.json'
  
cloud:
  project: 'plenary-genre-642'
  bucket: 'cory_kaggle'
  folder: 'elo'
  BQ_project: 'plenary-genre-642'
  BQ_datasource: 'kaggle_elo'